-- Preserve the actual web-push gateway result for user-facing diagnostics.
CREATE TABLE IF NOT EXISTS public.push_delivery_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    subscription_id bigint REFERENCES public.user_push_subscriptions(id) ON DELETE SET NULL,
    attempted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    status text NOT NULL CHECK (status IN ('accepted', 'failed')),
    status_code integer,
    error_message text
);

ALTER TABLE public.push_delivery_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'push_delivery_logs'
          AND policyname = 'Users can view their own push delivery diagnostics'
    ) THEN
        CREATE POLICY "Users can view their own push delivery diagnostics"
        ON public.push_delivery_logs
        FOR SELECT TO authenticated
        USING (auth.uid() = user_id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS push_delivery_logs_user_attempted_idx
    ON public.push_delivery_logs (user_id, attempted_at DESC);
