-- Create table for logging daily reminders sent to users
CREATE TABLE IF NOT EXISTS public.reminder_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    sent_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    streak integer NOT NULL,
    reminder_time text NOT NULL,
    notification_title text NOT NULL,
    notification_body text NOT NULL,
    status text NOT NULL,
    request_id bigint
);

-- Enable RLS on reminder_logs
ALTER TABLE public.reminder_logs ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own logs
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'reminder_logs' AND policyname = 'Users can view their own reminder logs'
    ) THEN
        CREATE POLICY "Users can view their own reminder logs" 
        ON public.reminder_logs 
        FOR SELECT 
        TO authenticated 
        USING (auth.uid() = user_id);
    END IF;
END
$$;
